name: "test-contracts"
on:
  push:
    branches:
      - main
    paths:
      - "contracts/contracts/**"
      - "contracts/test/**"
      - ".github/workflows/test-contracts.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contracts

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test
        env:
          HOT_WALLET_PRIVATE_KEY: ${{ secrets.HOT_WALLET_PRIVATE_KEY }}
